### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by FindHao** [google/tcmalloc#39]
OS: Ubuntu 18.04 x86_64
GCC 7.5.0
I followed the installation guide. When execute `bazel test //tcmalloc/...`, an error occurred. 

```
In file included from ./tcmalloc/huge_page_aware_allocator.h:25:0,
                 from tcmalloc/huge_page_aware_allocator.cc:15:
./tcmalloc/huge_page_filler.h: In instantiation of 'void tcmalloc::SkippedSubreleaseCorrectnessTracker<kEpochs>::ReportUpdatedPeak(tcmalloc::Length) [with long unsigned int kEpochs = 600; tcmalloc::Length = long unsigned int]':
./tcmalloc/huge_page_filler.h:242:9:   required from 'void tcmalloc::FillerStatsTracker<kEpochs>::Report(tcmalloc::FillerStatsTracker<kEpochs>::FillerStats) [with long unsigned int kEpochs = 600]'
./tcmalloc/huge_page_filler.h:1791:24:   required from 'void tcmalloc::HugePageFiller<TrackerType>::UpdateFillerStatsTracker() [with TrackerType = tcmalloc::PageTracker<tcmalloc::SystemRelease>]'
./tcmalloc/huge_page_filler.h:1289:27:   required from 'void tcmalloc::HugePageFiller<TrackerType>::Contribute(TrackerType*, bool) [with TrackerType = tcmalloc::PageTracker<tcmalloc::SystemRelease>]'
tcmalloc/huge_page_aware_allocator.cc:135:33:   required from here

./tcmalloc/huge_page_filler.h:89:5: error: no matching function for call to 'tcmalloc::TimeSeriesTracker<tcmalloc::SkippedSubreleaseCorrectnessTracker<600>::SkippedSubreleaseEntry, tcmalloc::SkippedSubreleaseCorrectnessTracker<600>::SkippedSubreleaseUpdate, 600>::Report(<brace-enclosed initializer list>)'
     if (tracker_.Report({.confirmed_peak = current_peak})) {
     ^~
```
Anybody can help?

**Comment by ckennelly** [comment]
I think this was introduced by ecbc1eec00197e58757f4a5fb1065512edb974c0.

It's using C++20's designated initializers, which wasn't supported until GCC 8 (per https://gcc.gnu.org/projects/cxx-status.html#cxx2a).
